"""Generate IK reference cases by calling the simulator's leg_ik on a grid
of foot positions around each leg's NEUTRAL_FOOT. Output is a C++ header
consumed by test_kinematics.

Run from the firmware directory:
    python test/gen_ik_reference.py
"""

import sys
from pathlib import Path

SIM_DIR = Path(__file__).resolve().parent.parent.parent / "simulation"
sys.path.insert(0, str(SIM_DIR))

from kinematics import NEUTRAL_FOOT, leg_ik

LEG_FW_TO_SIM = ["fr", "fl", "rr", "rl"]

DELTAS = [
    (0.000,  0.000,  0.000),
    (0.020,  0.000,  0.000),
    (-0.020, 0.000,  0.000),
    (0.000,  0.020,  0.000),
    (0.000, -0.020,  0.000),
    (0.000,  0.000,  0.015),
    (0.000,  0.000, -0.015),
    (0.020,  0.020, -0.010),
    (-0.020,-0.020,  0.010),
    (0.030,  0.030,  0.000),
    (-0.030,-0.030,  0.000),
    (0.040,  0.000,  0.020),
    (-0.040, 0.000, -0.020),
]

OUT = Path(__file__).resolve().parent / "test_kinematics" / "reference_data.h"


def main():
    cases = []
    for fw_id, sim_name in enumerate(LEG_FW_TO_SIM):
        nx, ny, nz = NEUTRAL_FOOT[sim_name]
        for dx, dy, dz in DELTAS:
            x, y, z = nx + dx, ny + dy, nz + dz
            s, h, k = leg_ik((x, y, z), sim_name)
            cases.append((fw_id, sim_name, x, y, z, s, h, k))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as f:
        f.write("#ifndef IK_REFERENCE_DATA_H\n")
        f.write("#define IK_REFERENCE_DATA_H\n\n")
        f.write("// AUTO-GENERATED by test/gen_ik_reference.py from sim leg_ik.\n")
        f.write("// Do not edit by hand.\n\n")
        f.write("struct IKRefCase {\n")
        f.write("    int   leg_id;\n")
        f.write("    float x, y, z;\n")
        f.write("    float shoulder, hip, knee;\n")
        f.write("};\n\n")
        f.write(f"static const int IK_REF_COUNT = {len(cases)};\n\n")
        f.write("static const IKRefCase IK_REF_CASES[IK_REF_COUNT] = {\n")
        for fw_id, name, x, y, z, s, h, k in cases:
            f.write(f"    {{ {fw_id}, {x:.6f}f, {y:.6f}f, {z:.6f}f, "
                    f"{s:.6f}f, {h:.6f}f, {k:.6f}f }}, // {name}\n")
        f.write("};\n\n")
        f.write("#endif\n")
    print(f"Wrote {len(cases)} cases to {OUT}")


if __name__ == "__main__":
    main()
