#!/usr/bin/env python3
"""Generate clip_parity_reference.h: expected servo triples from the Blender
exporter's _frame_to_servo, for sampled math-space inputs. The firmware's
translateToServo (applied to scale-from-N values) must match these within 1
degree. Mirrors gen_ik_reference.py. Run via:

    uv run python code/firmware/test/gen_clip_parity_reference.py
"""

import importlib.util
import json
import os
import sys

REPO = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
)
PANEL = os.path.join(
    REPO, "animation/addons/fh_clip_panel.py"
)  # moved scripts/->addons/ (2f627a1)
CONV = json.load(open(os.path.join(REPO, "animation/convention.json")))
OUT = os.path.join(
    os.path.dirname(__file__), "test_clip_parity", "clip_parity_reference.h"
)

# Reuse the bpy stub from test_servo_parity.py by importing it.
sys.path.insert(0, os.path.join(REPO, "animation/scripts"))
import test_servo_parity as tsp  # noqa: E402

tsp._stub_bpy()
spec = importlib.util.spec_from_file_location("fh_clip_panel", PANEL)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)

# Sample raw (math-space, pre-scale) joint values per leg; exercise sign mix.
SAMPLES = [
    {
        "fr": [45, -60, -37],
        "fl": [75, -60, -40],
        "br": [-45, -50, -50],
        "bl": [-135, -60, -35],
    },  # neutral
    {
        "fr": [60, -30, -10],
        "fl": [90, -40, -20],
        "br": [-30, -20, -30],
        "bl": [-120, -45, -25],
    },
    {
        "fr": [30, -80, -60],
        "fl": [60, -75, -55],
        "br": [-60, -70, -65],
        "bl": [-150, -70, -50],
    },
]
LEGS = ("fr", "fl", "br", "bl")
LEG_ID = {"fr": 0, "fl": 1, "br": 2, "bl": 3}

lines = [
    "#ifndef CLIP_PARITY_REFERENCE_H",
    "#define CLIP_PARITY_REFERENCE_H",
    "#include <stdint.h>",
    "// Auto-generated by gen_clip_parity_reference.py — do not edit.",
    "typedef struct { uint8_t leg_id; double sh, th, kn;"
    " double exp_hip, exp_thigh, exp_knee; } ClipParityCase;",
    "static const ClipParityCase CLIP_PARITY_CASES[] = {",
]
n = 0
for s in SAMPLES:
    row = {}
    for leg in LEGS:
        for j, link in enumerate(("link1", "link2", "link3")):
            row[f"{leg}_{link}"] = float(s[leg][j])
    servo = mod._frame_to_servo(row, CONV)  # scale-from-N + translateToServo + round
    scaled = mod._scale_from_neutral(row, CONV)  # math-space pre-scaled (header values)
    for leg in LEGS:
        sh, th, kn = scaled[leg]
        hip, thigh, knee = servo[leg]
        lines.append(
            f"  {{ {LEG_ID[leg]}, {sh:.6f}, {th:.6f}, {kn:.6f},"
            f" {hip:.1f}, {thigh:.1f}, {knee:.1f} }},"
        )
        n += 1
lines += ["};", f"#define CLIP_PARITY_COUNT {n}", "#endif"]
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write("\n".join(lines) + "\n")
print(f"wrote {OUT} ({n} cases)")
