// Clips bundled into the app at build time (assets/clips_extra.json, written by
// the FH Clip Panel exporter). Unlike the firmware clips listed over T:8, these
// don't need to be flashed: the app streams their math-space frames itself
// (T:12 CMD_STREAM_FRAME), and the firmware applies translateToServo + CALIB
// on receipt — so a newly authored animation is playable as soon as it's
// exported, with hardware calibration owned entirely by the firmware.
import clipsExtra from "../assets/clips_extra.json";

export type StreamFrame = {
  t: number; // ms from clip start
  fr: number[]; // [shoulder, thigh, knee] math-space joint degrees
  fl: number[];
  br: number[];
  bl: number[];
};

export type StreamClip = {
  name: string;
  frame_ms: number; // wall-clock period between frames (authored scene FPS)
  duration_ms: number;
  loop: boolean;
  frames: StreamFrame[];
};

type ClipsExtra = { wire?: string; clips: StreamClip[] };

const bundle = clipsExtra as ClipsExtra;

// Schema guard: the exporter tags math-space bundles with wire: "T12". A
// missing or wrong tag means the bundle was generated by an old CALIB-baked
// exporter and the angles can't be safely streamed through T:12.
if (bundle.wire !== "T12") {
  throw new Error(
    `clips_extra.json wire="${bundle.wire ?? "<missing>"}", expected "T12". ` +
      "Re-export from the FH Clip Panel (CALIB now owned by firmware, " +
      "see fh_clip_panel.py:to_clips_extra_json).",
  );
}

export const STREAM_CLIPS: StreamClip[] = bundle.clips;
