# code/simulation/pybullet_interpreter/clip_loader.py
"""Parse animation/exported_clips/clips_all.h into Python dataclasses.

The .h file is generated by the FH Clip Panel Blender add-on
(animation/addons/fh_clip_panel.py, function to_clips_header).

Frame data in clips_all.h:
  a[12] = PRE-SCALED math-space joint degrees.
  The 2/3 scale-from-NEUTRAL is already applied.
  Firmware LegId order: FR(sh,th,kn), FL(sh,th,kn), RR(sh,th,kn), RL(sh,th,kn).
  Firmware applies ONLY translateToServo() at runtime — not this module.

Do NOT re-apply scale-from-NEUTRAL here; the data is already in the
correct space for translate_to_servo().
"""

from dataclasses import dataclass, field
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CLIPS_H = _REPO_ROOT / "animation" / "exported_clips" / "clips_all.h"


@dataclass
class ClipFrame:
    """One keyframe from a clip.

    t_ms: timestamp in milliseconds (uint16 in firmware).
    a:    12 pre-scaled math-space angles [deg], firmware LegId order:
          a[0..2]  = FR  (sh, th, kn)
          a[3..5]  = FL  (sh, th, kn)
          a[6..8]  = RR  (sh, th, kn)
          a[9..11] = RL  (sh, th, kn)
    """

    t_ms: int
    a: list[float] = field(default_factory=list)


@dataclass
class ClipData:
    """Parsed clip, ready for clip_player.py.

    name:        human-readable clip name (e.g. "tiny wiggle").
    frames:      list of ClipFrame, in ascending t_ms order.
    frame_count: number of frames (== len(frames)).
    duration_ms: total clip duration in milliseconds.
    """

    name: str
    frames: list[ClipFrame] = field(default_factory=list)
    frame_count: int = 0
    duration_ms: int = 0


def load_clips_all_h(path: Path = DEFAULT_CLIPS_H) -> list[ClipData]:
    """Parse a clips_all.h file and return all clips.

    Input:  path to a clips_all.h generated by fh_clip_panel.py.
    Output: list of ClipData, in the order they appear in FH_CLIPS[].

    The parser uses regex; it handles the exact format emitted by
    to_clips_header() in fh_clip_panel.py. If the format changes,
    update the regexes here.

    Raises FileNotFoundError if path does not exist.
    Raises ValueError if no clips are found (likely a format mismatch).
    """
    raise NotImplementedError


def get_clip_by_name(clips: list[ClipData], name: str) -> ClipData:
    """Return the clip whose name matches (case-insensitive), or raise KeyError.

    Input:  clips list from load_clips_all_h(), clip name string.
    Output: matching ClipData.
    Raises: KeyError with available names if no match found.
    """
    raise NotImplementedError
